<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <Deterministic>true</Deterministic>
    <AssemblyName>PluginManager.Interop</AssemblyName>
    <RootNamespace>PluginManager.Interop</RootNamespace>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Label="Package">
    <Title>Plugin Manager Interop</Title>
    <Description>Interop contracts and base classes for plugin communication and hosting.</Description>
    <PackageProjectUrl>https://github.com/supermemo/PluginManager</PackageProjectUrl>
    <PackageReleaseNotes></PackageReleaseNotes>
    <PackageTags>PluginManager,Interop,Contracts</PackageTags>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>pdbonly</DebugType>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Runtime.Remoting" />
    <Reference Include="System.Xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PluginManager.PluginHost\PluginManager.PluginHost.csproj" />
  </ItemGroup>

  <Target Name="NuPack" AfterTargets="Build" Condition=" $(RunNuPack) == 'True' ">
    <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
      <Output TaskParameter="Assemblies" ItemName="myAssemblyInfo" />
    </GetAssemblyIdentity>
    <ItemGroup>
      <NuGetExe Include="$(SolutionDir)tools\nuget.exe" />
      <VersionNumber Include="@(myAssemblyInfo->'%(Version)')" />
    </ItemGroup>
    <Exec Command="&quot;%(NuGetExe.FullPath)&quot; pack $(AssemblyName).nuspec -Version @(VersionNumber) -Properties Configuration=$(Configuration) -OutputDirectory $(SolutionDir)Releases -BasePath $(OutDir)" />
  </Target>

</Project>